### Introducción

Esta es una introducción cortita a pandas, sobre todo para los que no lo usaron nunca. Se pueden encontrar ejemplos más complejos en este <a href="https://pandas.pydata.org/docs/user_guide/cookbook.html#cookbook" target="_blank">link<a/>.

Lo importamos junto a *numpy*:

In [1]:
import numpy as np
import pandas as pd

## Creación del objeto

Revisar: <a target="_blank" href="https://pandas.pydata.org/docs/user_guide/dsintro.html#dsintro">Introducción a la estructura de datos</a>.

Crear una <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series">`series`</a> pasándole una lista de valores, dejándole crear a pandas los índices por default:

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

¿Qué estamos viendo acá arriba?

Creando un <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">`DataFrame`</a> pasándole un *numpy* array, con fechas como índices usando <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.date_range.html#pandas.date_range">`date_range()`</a> y le ponemos nombre a las columnas:

In [10]:
dates = pd.date_range("20130101", periods=6, freq="M")
dates

DatetimeIndex(['2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30',
               '2013-05-31', '2013-06-30'],
              dtype='datetime64[ns]', freq='M')

In [11]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['HOLA', 'B', 'C', 'd'])
df

                HOLA         B         C         d
2013-01-31 -0.414885 -1.685121  2.019380 -0.373253
2013-02-28 -0.249282  0.692056 -1.408319  0.457253
2013-03-31  0.037132  2.289854 -1.447822  0.337011
2013-04-30 -2.210928  0.969538  0.795584  0.393443
2013-05-31  0.950337  1.229045 -1.289182  0.652677
2013-06-30 -0.497768  0.658451 -0.421317  0.123047

También podemos crear un <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">`DataFrame`</a> pasándole un diccionario de objetos que pueden ser convertidos a una estructura como la que vimos de *Series*:

In [6]:
lista = [3] * 6
lista

[3, 3, 3, 3, 3, 3]

In [7]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Podemos ver que las columnas resultantes del <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">`DataFrame`</a> tienen diferentes <a target="_blank" href="https://pandas.pydata.org/docs/user_guide/basics.html#basics-dtypes">`dtypes`</a>:

In [ ]:
df2.dtypes

## Observando la data

Ver la sección de <a target="_blank" href="https://pandas.pydata.org/docs/user_guide/basics.html#basics">Basics</a>.

Usar <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html#pandas.DataFrame.head">`DataFrame.head()`</a> y <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.tail.html#pandas.DataFrame.tail">`DataFrame.tail()`</a> para ver las filas de arriba y de abajo del frame:

In [12]:
df.head(2)

                HOLA         B         C         d
2013-01-31 -0.414885 -1.685121  2.019380 -0.373253
2013-02-28 -0.249282  0.692056 -1.408319  0.457253

In [13]:
df.tail(3)  # ¿Qué hace el 3?

                HOLA         B         C         d
2013-04-30 -2.210928  0.969538  0.795584  0.393443
2013-05-31  0.950337  1.229045 -1.289182  0.652677
2013-06-30 -0.497768  0.658451 -0.421317  0.123047

Mostrar el índice del <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.index.html#pandas.DataFrame.index">`DataFrame.index`</a> o las columnas <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.columns.html#pandas.DataFrame.columns">`DataFrame.columns`</a>:

In [14]:
df.index

DatetimeIndex(['2013-01-31', '2013-02-28', '2013-03-31', '2013-04-30',
               '2013-05-31', '2013-06-30'],
              dtype='datetime64[ns]', freq='M')

In [ ]:
df.columns

<a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy">`DataFrame.to_numpy()`</a> nos da una representación de *NumPy*. Notar que esta puede ser una operación cara si tu <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">`DataFrame`</a> tiene columnas de distintos tipo de dato, que es una diferencia fundamental entre *pandas* y *numpy*: **NumPy arrays tienen un dtype para el array entero, mientras que pandas DataFrames tienen un dtype por columna**. Cuando llamás <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy">`DataFrame.to_numpy()`</a>, pandas va a encontrar el *NumPy dtype* que pueda tener todos los *dtypes* en el *DataFrame*. Probablemente termine usando `object`, que requiere castear cada valor a un Python object... Lento.

Para `df`, que es nuestro <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">`DataFrame`</a>, tiene todos los valores floating-point, y <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy">`DataFrame.to_numpy()`</a> es rápido y no requiere copiar data:

In [15]:
df.to_numpy()

array([[-0.41488473, -1.68512123,  2.01938028, -0.37325271],
       [-0.24928227,  0.69205568, -1.40831887,  0.45725308],
       [ 0.03713154,  2.28985441, -1.44782213,  0.3370112 ],
       [-2.21092788,  0.96953798,  0.79558416,  0.39344268],
       [ 0.95033735,  1.22904496, -1.28918191,  0.65267652],
       [-0.49776778,  0.65845064, -0.4213174 ,  0.12304693]])

Para `df2`, el <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame">`DataFrame`</a> con múltiples dtypes, <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy">`DataFrame.to_numpy()`</a> es relativamente caro:

In [16]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

NOTE: <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_numpy.html#pandas.DataFrame.to_numpy">`DataFrame.to_numpy()`</a> no incluye ni el índice ni los títulos (labels) de las columnas.

Transponiendo la data:

In [17]:
df.T

      2013-01-31  2013-02-28  2013-03-31  2013-04-30  2013-05-31  2013-06-30
HOLA   -0.414885   -0.249282    0.037132   -2.210928    0.950337   -0.497768
B      -1.685121    0.692056    2.289854    0.969538    1.229045    0.658451
C       2.019380   -1.408319   -1.447822    0.795584   -1.289182   -0.421317
d      -0.373253    0.457253    0.337011    0.393443    0.652677    0.123047

<a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_index.html#pandas.DataFrame.sort_index">`DataFrame.sort_index()`</a> ordena según el eje:

In [18]:
df.sort_index(axis=1, ascending=False)

                   d      HOLA         C         B
2013-01-31 -0.373253 -0.414885  2.019380 -1.685121
2013-02-28  0.457253 -0.249282 -1.408319  0.692056
2013-03-31  0.337011  0.037132 -1.447822  2.289854
2013-04-30  0.393443 -2.210928  0.795584  0.969538
2013-05-31  0.652677  0.950337 -1.289182  1.229045
2013-06-30  0.123047 -0.497768 -0.421317  0.658451

<a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values">`DataFrame.sort_values()`</a> ordena por valores:

In [ ]:
df.sort_values(by='B')

## Selección

NOTE: Mientras que los métodos estándar de Python / NumPy para seleccionar son intuitivos, en la realidad se usan los métodos optimizados de pandas para acceder a los datos, <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at">`DataFrame.at()`</a>, <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iat.html#pandas.DataFrame.iat">`DataFrame.iat()`</a>, <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc">`DataFrame.loc()`</a> y <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc">`DataFrame.iloc()`</a>.

La documentación de indexing: <a target="_blank" href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing">Indexing and Selecting Data</a> y <a target="_blank" href="https://pandas.pydata.org/docs/user_guide/advanced.html#advanced">MultiIndex / Advanced Indexing</a>.

### Getting

Seleccionar una columna, que devuelve una <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series">`Series`</a>, equivalente a `df.A`:

In [ ]:
df[["C", "B"]]

Seleccionando via `[]` (`__getitem__`), que hace slices de las filas:

In [ ]:
df[0:3]

In [ ]:
df["20130102":"20130104"]

### Selection by label

Ver más en <a target="_blank" href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-label">Selection by Label</a> usando <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.loc.html#pandas.DataFrame.loc">`DataFrame.loc()`</a> o <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at">`DataFrame.at()`</a>.

Para obtener una selección cruzada utilizando el "label":

In [ ]:
dates[0]

In [ ]:
df.loc[dates[0]]

Seleccionando multi-axis por label:

In [ ]:
df.loc[:, ["A", "B"]]

label slicing, a diferencia de lo que vimos en Python hasta ahora, incluye tanto el primero como el último:

In [ ]:
df.loc["20130102":"20130104", ["A", "B"]]

Reducción de las dimensiones del objeto devuelto:

In [ ]:
df.loc["20130102", ["A", "B"]]

Para obtener un valor escalar:

In [ ]:
df.loc[dates[0], "A"]

Equivalente al método anterior:

In [ ]:
df.at[dates[0], "A"]

### Selección por posición

Ver más: <a target="_blank" href="https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-integer">Selection by Position</a> usando <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.iloc.html#pandas.DataFrame.iloc">`DataFrame.iloc()`</a> o <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.at.html#pandas.DataFrame.at">`DataFrame.at()`</a>.

Seleccionar via la posición de los enteros que le pasamos:

In [ ]:
df

In [ ]:
df.iloc[3]

Por slices de enteros, como en NumPy/Python:

In [ ]:
df.iloc[3:5, 0:2]

Por listas de enteros similar al estilo de NumPy/Python:

In [ ]:
df.iloc[[1, 2, 4], [0, 2]]

Para hacer slicing de filas explícitamente:

In [ ]:
df.iloc[1:3, :]

Lo mismo pero para columnas:

In [ ]:
df.iloc[:, 1:3]

Para obtener el valor explícito:

In [ ]:
df.iloc[1, 1]

Equivalente a lo anterior:

In [ ]:
df.iat[1, 1]

### Boolean indexing

Usar el valor de una columna para seleccionar los datos:

In [20]:
df["HOLA"] > 0

2013-01-31    False
2013-02-28    False
2013-03-31     True
2013-04-30    False
2013-05-31     True
2013-06-30    False
Freq: M, Name: HOLA, dtype: bool

In [ ]:
df[df["HOLA"] > 0]

                HOLA         B         C         d
2013-03-31  0.037132  2.289854 -1.447822  0.337011
2013-05-31  0.950337  1.229045 -1.289182  0.652677

Seleccionar los valores de un DataFrame donde una condición se cumple:

In [ ]:
df[df > 0]

                HOLA         B         C         d
2013-01-31 -0.414885 -1.685121  2.019380 -0.373253
2013-02-28 -0.249282  0.692056 -1.408319  0.457253
2013-03-31  0.037132  2.289854 -1.447822  0.337011
2013-04-30 -2.210928  0.969538  0.795584  0.393443
2013-05-31  0.950337  1.229045 -1.289182  0.652677
2013-06-30 -0.497768  0.658451 -0.421317  0.123047

Usando el método <a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.Series.isin.html#pandas.Series.isin">`isin()`</a> para filtrar:

In [ ]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2

In [ ]:
df2[df2["E"].isin(["two", "four"])]

### Setting

Setear una columna automáticamente te alinea los datos por los índices:

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range("20130102", periods=6))
s1

In [ ]:
df["F"] = s1

Setear valores por label:

In [ ]:
df.at[dates[0], "A"] = 0

Setear valores por posición:

In [ ]:
df.iat[0, 1] = 0

Setear valores asignando con NumPy array:

In [ ]:
df.loc[:, "D"] = np.array([5] * len(df))

El resultado:

In [ ]:
df

La operación `where`:

In [ ]:
df2 = df.copy()
df2[df2 > 0] = -df2
df2

## Missing data

pandas primeramente usa el `np.nan` para representar la data faltante. Por default no se incluye en los cálculos. Ver la sección [Missing Data](https://pandas.pydata.org/docs/user_guide/missing_data.html#missing-data).

Reindexar permite cambiar/agregar/borrar el índice de un eje especificado. Esto devuelve una copia de la data:

In [ ]:
df1 = df.reindex(index = dates[0:4], columns = list(df.columns) + ['E'])
df1.loc[dates[0] : dates[1], 'E'] = 1
df1

[`DataFrame.dropna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html#pandas.DataFrame.dropna) tira todas las filas que tengan datos faltante:

In [ ]:
df1.dropna(how='any')

[`DataFrame.fillna()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.fillna.html#pandas.DataFrame.fillna) llena la data faltante:

In [ ]:
df1.fillna(value=5)

[`isna()`](https://pandas.pydata.org/docs/reference/api/pandas.isna.html#pandas.isna) toma la "máscara" donde los valores son `nan`:

In [ ]:
pd.isna(df)

## Operations

Ver [Basic section on Binary Ops](https://pandas.pydata.org/docs/user_guide/basics.html#basics-binop).

### Stats

Las operaciones en general *excluyen* missing data.

Haciendo estadística descriptiva:

In [ ]:
df.mean()

Misma operación en el otro eje:

In [ ]:
df.mean(1)

Operando con objetos que tienen distintas dimensiones y necesitan alinearse. Además, pandas automáticamente extiende la dimensión especificada:

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index = dates).shift(2)
s

In [ ]:
df.sub(s, axis='index')

### Apply

[`DataFrame.apply()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html#pandas.DataFrame.apply) aplica una función definida por el usuario a los datos:

In [ ]:
df.apply(np.cumsum)

In [ ]:
df.apply(lambda x: x.max() - x.min())

### Histograma

Ver más [Histogramming and Discretization](https://pandas.pydata.org/docs/user_guide/basics.html#basics-discretization).

In [ ]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

In [ ]:
s.value_counts()

### Métodos de Strings

Series está equipada con un set de métodos para procesar los `str` que hacen más fácil operar con cada elemento del array, como en el snippet de abajo. Notar que el pattern-matching en `str` generalmente usa [regular expressions](https://docs.python.org/3/library/re.html) por default (y en algunos casos lo usa siempre). Ver más [Vectorized String Methods](https://pandas.pydata.org/docs/user_guide/text.html#text-string-methods).

In [ ]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])
s.str.lower()

## Merge

### Concat

Ver [Merging section](https://pandas.pydata.org/docs/user_guide/merging.html#merging).

Concatenar con [`concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html#pandas.concat):

In [ ]:
df = pd.DataFrame(np.random.randn(10, 4))
df

In [ ]:
# break it onto pieces
pieces = [df[:3], df[3:7], df[7:]]

pd.concat(pieces)

NOTE: Agregar columnas a un [`DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame) is relativamente rápido. Sin embargo, agregar una fila requiere una copia, y puede ser caro.

### Join

[`merge()`](https://pandas.pydata.org/docs/reference/api/pandas.merge.html#pandas.merge) habilita el estilo de SQL para hacer join sobre las columnas especificadas. Ver [Database style joining](https://pandas.pydata.org/docs/user_guide/merging.html#merging-join).

In [ ]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})
print(left)
print(right)
pd.merge(left, right, on="key")

Otro ejemplo:

In [ ]:
left = pd.DataFrame({"key": ["foo", "bar"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "bar"], "rval": [4, 5]})
print(left)
print(right)
pd.merge(left, right, on="key")

## Grouping

Por 'group by' nos referimos a un proceso que incluye uno o más pasos de los que siguen:


*   **Splitting** (partiendo) los datos en grupos según algún criterio
*   **Applying** (aplicando) una función a cada grupo independientemente
*   **Combining** (combinando) los resultados en una estructura

Ver [Grouping section](https://pandas.pydata.org/docs/user_guide/groupby.html#groupby).

In [ ]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
                         'foo', 'bar', 'foo', 'bar'],
                   'B': ['one', 'one', 'two', 'three',
                         'two', 'two', 'one', 'three'],
                   'C': np.random.randn(8),
                   'D': np.random.randn(8)})
df

Agrupando y después aplicando la función `sum()` al grupo resultante:

In [ ]:
df.groupby('A')[["C", "D"]].sum()

In [ ]:
df.groupby(["A", "B"]).sum()

## Reshaping

Ver [Hierarchical Indexing](https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-hierarchical) y [Reshaping](https://pandas.pydata.org/docs/user_guide/reshaping.html#reshaping-stacking).

### Stack

In [ ]:
tuples = list(
    zip(
        ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
        ["one", "two", "one", "two", "one", "two", "one", "two"],
    )
)

index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])

df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=["A", "B"])
df2 = df[:4]
df2

The [`stack()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html#pandas.DataFrame.stack) method “compresses” a level in the DataFrame’s columns:

In [ ]:
stacked = df2.stack()
stacked

With a “stacked” DataFrame or Series (having a [MultiIndex](https://pandas.pydata.org/docs/reference/api/pandas.MultiIndex.html#pandas.MultiIndex) as the `index`), the inverse operation of [`stack()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.stack.html#pandas.DataFrame.stack) is [`unstack()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.unstack.html#pandas.DataFrame.unstack), which by default unstacks the **last level**:

In [ ]:
stacked.unstack()

In [ ]:
stacked.unstack(1)

In [ ]:
stacked.unstack(0)

### Pivot tables

See the section on [Pivot Tables](https://pandas.pydata.org/docs/user_guide/reshaping.html#reshaping-pivot).

In [ ]:
df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)
df

[`pivot_table()`](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html#pandas.pivot_table) pivots a [`DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame) specifying the `values`, `index`, and `columns`

In [ ]:
pd.pivot_table(df, values="D", index=["A", "B"], columns=["C"])

## Time series

pandas has simple, powerful, and efficient functionality for performing resampling operations during frequency conversion (e.g., converting secondly data into 5-minutely data). This is extremely common in, but not limited to, financial applications. See the [Time Series](https://pandas.pydata.org/docs/user_guide/timeseries.html#timeseries) section.

In [ ]:
rng = pd.date_range("1/1/2012", periods=100, freq="S")
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)
ts.resample("5Min").sum()

[`Series.tz_localize()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.tz_localize.html#pandas.Series.tz_localize) localizes a time series to a time zone:

In [ ]:
rng = pd.date_range("3/6/2012 00:00", periods=5, freq="D")
ts = pd.Series(np.random.randn(len(rng)), rng)
print(ts, "\n")
ts_utc = ts.tz_localize("UTC")
ts_utc

Converting between time span representations:

In [ ]:
rng = pd.date_range("1/1/2012", periods=5, freq="M")
ts = pd.Series(np.random.randn(len(rng)), index=rng)
ps = ts.to_period()
ps

In [ ]:
ps.to_timestamp()

Converting between period and timestamp enables some convenient arithmetic functions to be used. In the following example, we convert a quarterly frequency with year ending in November to 9am of the end of the month following the quarter end:

In [ ]:
prng = pd.period_range("1990Q1", "2000Q4", freq="Q-NOV")
ts = pd.Series(np.random.randn(len(prng)), prng)
ts.index = (prng.asfreq("M", "e") + 1).asfreq("H", "s") + 9
ts.head()

## Categoricals

pandas can include categorical data in a [`DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame). For full docs, see the [categorical introduction](https://pandas.pydata.org/docs/user_guide/categorical.html#categorical) and the [API documentation](https://pandas.pydata.org/docs/reference/arrays.html#api-arrays-categorical).

In [ ]:
df = pd.DataFrame(
    {"id": [1, 2, 3, 4, 5, 6], "raw_grade": ["a", "b", "b", "a", "a", "e"]}
)
df

Converting the raw grades to a categorical data type:

In [ ]:
df["grade"] = df["raw_grade"].astype("category")
df["grade"]

Rename the categories to more meaningful names:

In [ ]:
new_categories = ["very good", "good", "very bad"]
df["grade"] = df["grade"].cat.rename_categories(new_categories)
df

Reorder the categories and simultaneously add the missing categories (methods under [`Series.cat()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.cat.html#pandas.Series.cat) return a new [`Series`](https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series) by default):

In [ ]:
df["grade"] = df["grade"].cat.set_categories(
    ["very bad", "bad", "medium", "good", "very good"]
)
df["grade"]

Sorting is per order in the categories, not lexical order:

In [ ]:
df.sort_values(by="grade")

Grouping by a categorical column also shows empty categories:

In [ ]:
df.groupby("grade").size()

## Plotting

See the [Plotting](https://pandas.pydata.org/docs/user_guide/visualization.html#visualization) docs.

We use the standard convention for referencing the matplotlib API:

In [ ]:
import matplotlib.pyplot as plt
plt.close("all")

ts = pd.Series(np.random.randn(1000), index=pd.date_range("1/1/2000", periods=1000))
ts = ts.cumsum()
ts.plot();

If running under Jupyter Notebook, the plot will appear on [`plot()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.plot.html#pandas.Series.plot). Otherwise use [`matplotlib.pyplot.show`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.show.html) to show it or [`matplotlib.pyplot.savefig`](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.savefig.html) to write it to a file.

On a DataFrame, the [`plot()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.html#pandas.DataFrame.plot) method is a convenience to plot all of the columns with labels:

In [ ]:
df = pd.DataFrame(
    np.random.randn(1000, 4), index=ts.index, columns=["A", "B", "C", "D"]
)

df = df.cumsum()
plt.figure();
df.plot();
plt.legend(loc='best');

## Importando y exportando data

### CSV

[Writing to a csv file](https://pandas.pydata.org/docs/user_guide/io.html#io-store-in-csv): using [`DataFrame.to_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv)

In [ ]:
df.to_csv("foo.csv")

[Reading from a csv file](https://pandas.pydata.org/docs/user_guide/io.html#io-read-csv-table): using [`read_csv()`](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html#pandas.read_csv)

In [ ]:
pd.read_csv("foo.csv")

### HDF5

Reading and writing to [HDFStores](https://pandas.pydata.org/docs/user_guide/io.html#io-hdf5).

Writing to a HDF5 Store using [`DataFrame.to_hdf()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_hdf.html#pandas.DataFrame.to_hdf):

In [ ]:
df.to_hdf("foo.h5", "df")

Reading from a HDF5 Store using [`read_hdf()`](https://pandas.pydata.org/docs/reference/api/pandas.read_hdf.html#pandas.read_hdf):

In [ ]:
pd.read_hdf("foo.h5", "df")

### Excel

Reading and writing to [Excel](https://pandas.pydata.org/docs/user_guide/io.html#io-excel).

Writing to an excel file using [`DataFrame.to_excel()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_excel.html#pandas.DataFrame.to_excel):

In [ ]:
df.to_excel("foo.xlsx", sheet_name="Sheet1")

Reading from an excel file using [`read_excel()`](https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html#pandas.read_excel):

In [ ]:
pd.read_excel("foo.xlsx", "Sheet1", index_col=None, na_values=["NA"])

## Gotchas

If you are attempting to perform a boolean operation on a [`Series`](https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series) or [`DataFrame`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame) you might see an exception like:

In [ ]:
if pd.Series([False, True, False]):
     print("I was true")

See [Comparisons](https://pandas.pydata.org/docs/user_guide/basics.html#basics-compare) and [Gotchas](https://pandas.pydata.org/docs/user_guide/gotchas.html#gotchas) for an explanation and what to do.

<a target="_blank" href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html#pandas.DataFrame.describe">`describe()`</a> muestra una estadística rápida de la data:

In [ ]:
df.describe()